alias cd="z"
alias grep="rg"
alias ls="eza -1 -l -F --color=always --time-style=iso --git"
alias tree="br"
alias reload-dock="defaults write com.apple.dock ResetLaunchPad -bool TRUE; killall Dock"
alias zsh_dir="cd $ZDOTDIR"
alias zsh_config="nano $ZDOTDIR/.zshrc && source $ZDOTDIR/.zshrc && neofetch"
alias zsh_env="nano $ZDOTDIR/.zshenv && source $ZDOTDIR/.zshenv && neofetch"
alias zsh_alias="nano $ZDOTDIR/alias.zsh && source $ZDOTDIR/alias.zsh && neofetch"
alias zsh_path="nano $ZDOTDIR/path.zsh && source $ZDOTDIR/path.zsh && neofetch"
alias zsh_plugin="nano $ZDOTDIR/plugin.zsh && source $ZDOTDIR/plugin.zsh"
alias zsh_func="nano $ZDOTDIR/func.zsh && source $ZDOTDIR/func.zsh"
alias wget="wget --hsts-file='$XDG_DATA_HOME/wget-hsts'"
alias adb="HOME='$XDG_DATA_HOME'/android adb"
