# homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"
# cargo
export PATH="$CARGO_HOME/bin:$PATH"
# pyenv
export PATH="$PYENV_ROOT/bin:$PATH"
# openjdk
export PATH="$HOMEBREW_PREFIX/opt/openjdk@17/bin:$PATH"
export PATH="$HOMEBREW_PREFIX/opt/openjdk/bin:$PATH"
# pnpm
export PATH="$PNPM_HOME:$PATH"
# volta
export PATH="$VOLTA_HOME/bin:$PATH"
# ccache
export PATH="$HOMEBREW_PREFIX/opt/ccache/libexec:$PATH"
# maven
export PATH="$HOMEBREW_PREFIX/Cellar/maven/3.9.3/libexec:$PATH"
# uutil-coreutils
export PATH="$HOMEBREW_PREFIX/opt/uutils-coreutils/libexec/uubin:$PATH"
# gnu-sed
export PATH="$HOMEBREW_PREFIX/opt/gnu-sed/libexec/gnubin:$PATH"
